EventManager/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^', include('sessao.urls')),
	url(r'^', include('recomendacao.urls')),
	url(r'^', include('topicos.urls')),
	url(r'^', include('login.urls')),
	url(r'^', include('trabalho.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/urls.py
from django.conf.urls import url

from django.contrib.auth import views
from .forms import LoginForm, UpdatePasswordForm

urlpatterns = [
  url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
  url(r'^trocar_senha/$', views.password_change,
    {
      'template_name': 'trocar_senha.html',
      'password_change_form': UpdatePasswordForm,
      'post_change_redirect': 'change_password',
    },
    name='change_password'),
  url(r'^logout/$', views.logout, {'next_page': 'login'}, name='logout'),
]

sessao/urls.py
from django.conf.urls import url
from django.shortcuts import redirect
from .views import sessoes, Sessao, excluir_sessao

urlpatterns = [
	url(r'^sessao/$', Sessao.as_view(), name='sessao'),
	url(r'^sessoes/$', sessoes, name='sessoes'),
	url(r'^excluir_sessao/$', excluir_sessao, name='excluir_sessao'),
  url(r'^$', lambda x: redirect(sessoes), name='home'),
]

sessao/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from firebase.backend import firebase
from datetime import datetime
import re

class Sessao(models.Model):
	class Meta:
		verbose_name = "Sessão"
		verbose_name_plural = "Sessões"

	nome = models.CharField(max_length=300)
	descricao = models.TextField()
	capacidade = models.IntegerField()
	sala = models.CharField(max_length=25)
	tipo = models.CharField(max_length=70)
	data = models.DateField()
	hora_inicio = models.TimeField()
	hora_fim = models.TimeField()
	key = models.CharField(max_length=30, editable=False)
	topicos_interesse = models.TextField()

	def __unicode__(self):
		return self.nome

	def save(self, *args, **kwargs):
		db = firebase.database()
		timestamp_start = datetime.combine(self.data, self.hora_inicio)
		timestamp_end = datetime.combine(self.data, self.hora_fim)
		topicos_db = db.child('topicos_interesse').get()

		# pega a string dos tópicos selecionados para a sessão e transforma em uma lista, usando expressão regular
		tp = re.findall(r"'(.*?)'", self.topicos_interesse, re.DOTALL)
		topicos_interesse = [ int(x) for x in tp ]

		# cria o dict que armazena as informações dos tópicos da sessão
		topicos = {}
		for topico in topicos_interesse:
			topicos[topico] = topicos_db.val()[topico]

		dados = {
			'nome': self.nome,
			'descricao': self.descricao,
			'capacidade': self.capacidade,
			'sala': self.sala,
			'tipo': self.tipo,
			'timestamp_start': long(timestamp_start.strftime("%s")),
			'timestamp_end': long(timestamp_end.strftime("%s")),
			'topicos_interesse': topicos
		}

		if not self.key:
			salvo = db.child('sessoes').push(dados)
			self.key = salvo['name']
		else:
			db.child('sessoes').child(self.key).update(dados)

	def delete(self):
		db = firebase.database()
		db.child('sessoes').child(self.key).remove()

sessao/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Sessao
from django_select2.forms import Select2MultipleWidget

class SessaoForm(forms.ModelForm):

	key = forms.CharField(widget=forms.HiddenInput(), required=False)
	nome = forms.CharField(label='Nome', widget=forms.TextInput(attrs={'class': 'form-control'}))
	descricao = forms.CharField(label='Descrição', widget=forms.Textarea(attrs={'class': 'form-control'}))
	capacidade = forms.DecimalField(label='Capacidade', widget=forms.TextInput(attrs={'class': 'form-control'}))
	sala = forms.CharField(label='Sala', widget=forms.TextInput(attrs={'class': 'form-control'}))
	tipo = forms.CharField(label='Tipo', widget=forms.TextInput(attrs={'class': 'form-control'}))
	data = forms.DateField(label='Data', widget=forms.DateInput(attrs={'class': 'form-control'}))
	hora_inicio = forms.TimeField(label='Hora de Início', widget=forms.TimeInput(attrs={'class': 'form-control'}))
	hora_fim = forms.TimeField(label='Hora de Término', widget=forms.TimeInput(attrs={'class': 'form-control'}))
	topicos_interesse = forms.CharField(label='Tópicos de Interesse', widget=Select2MultipleWidget, required=False)

	class Meta:
		model = Sessao
		fields = '__all__'

sessao/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import logging
import json

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.views import View
from django.core.urlresolvers import reverse
from datetime import datetime

from firebase.backend import firebase
from .models import Sessao
from .forms import SessaoForm

logger = logging.getLogger(__name__)

class Sessao(View):
	@method_decorator(login_required)
	def get(self, request):
		db = firebase.database()
		# pega os tópicos para popular as options do select no template
		topicos_db = db.child('topicos_interesse').get()
		topicos_interesse = []
		for t in topicos_db.each():
			try:
				topico = {}
				topico['text'] = t.val()
				topico['id'] = t.key()
				topicos_interesse.append(topico)
			except Exception as e:
				logger.warning('Erro com o Tópico: %s', e)

		# inicia a criaçao do formulário
		try:
			# caso exista uma key, será retornado um form populado com as informações do firebase para edição
			key = request.GET.get('key')
			sessao_db = db.child('sessoes').child(key).get().val()

			topicos_sessao = []
			try:
				topicos_sessao_db = db.child('sessoes').child(key).child('topicos_interesse').get()
				# pega os tópicos da sessão para popular o select no template
				for tp in topicos_sessao_db.each():
					topicos_sessao.append(int(tp.key()))
			except:
				logger.error('Não existem tópicos para essa sessão')

			# popula o form com as informações da sessão
			form = SessaoForm(
				initial={
					'key': key,
					'nome': sessao_db['nome'],
					'descricao': sessao_db['descricao'],
					'capacidade': sessao_db['capacidade'],
					'sala': sessao_db['sala'],
					'tipo': sessao_db['tipo'],
					'data': datetime.fromtimestamp(long(sessao_db['timestamp_start'])).date(),
					'hora_inicio': datetime.fromtimestamp(long(sessao_db['timestamp_start'])).time(),
					'hora_fim': datetime.fromtimestamp(long(sessao_db['timestamp_end'])).time(),
				}
			)
			# prepara o conteúdo que vai pro template
			# pra chamar no template tem que usar o nome que está entre aspas simples
			contexto = {
				'form': form,
				'topicos': topicos_sessao,
				'topicos_interesse': json.dumps(topicos_interesse)
			}
		except Exception as e:
			# do contrário, será retornado um form vazio, que será usado para a criação de um novo objeto
			form = SessaoForm()

			contexto = {
				'form': form,
				'topicos_interesse': json.dumps(topicos_interesse)
			}

		return render(request, 'sessao.html', contexto)

	@method_decorator(login_required)
	def post(self, request):
		form = SessaoForm(request.POST or None)
		if form.is_valid():
			# vai pegar a key, mesmo que ela seja vazia
			# caso a key seja vazia, é sinal de que o objeto é novo
			key = form.cleaned_data['key']
			# cria um objeto mas não salva, pois o commit=False
			sessao = form.save(commit=False)
			# Esse objeto não tem uma key definida, mas a key existe no formulário
			# Então é necessário passar a key da sessão editada para que uma nova sessão não seja criada
			sessao.key = key
			# salva o objeto editado
			sessao.save()
			logger.info('Sessão salva com sucesso: %s', sessao.key)
			messages.success(request, 'Sessão salva com sucesso!')

			if 'salvar' in request.POST:
				url = reverse('sessao')
				return redirect(url + '?key=' + sessao.key)
			elif 'salvar_novo' in request.POST:
				return redirect('sessao')
			else:
				return redirect('sessoes')
		else:
			contexto = {'form': form}
			return render(request, 'sessao.html', contexto)

@login_required
def excluir_sessao(request):
	if request.method == 'POST':
		db = firebase.database()
		item = request.POST.get('item')
		sessao = db.child('sessoes').child(item).get().val()
		if sessao:
			db.child('sessoes').child(item).remove()
			messages.success(request, 'Sessão removida com sucesso!')
			return HttpResponse('True')
		else:
			messages.error(request, 'Erro ao remover a sessão!')
			return HttpResponse('False')
	else:
		return redirect('sessoes')

@login_required
def sessoes(request):
	db = firebase.database()
	sessoes_fb = db.child('sessoes').get().val()
	sessoes = []

	try:
		for pk, s in sessoes_fb.items():
			try:
				sessao = {}
				sessao['key'] = pk
				sessao['nome'] = s['nome']
				sessao['descricao'] = s['descricao']
				sessao['capacidade'] = s['capacidade']
				sessao['sala'] = s['sala']
				sessao['tipo'] = s['tipo']
				sessoes.append(sessao)
			except KeyError as e:
				logger.error('Não foi possível carregar a sessão: %s', e)
	except AttributeError as e:
		logger.info('Não existem sessões cadastradas!')
		messages.info(request, 'Não existem sessões cadastradas!')

	contexto = {'sessoes': sessoes}

	return render(request, 'sessoes.html', contexto)

sessao/templates/sessao.html
{% extends "base.html" %}
{% load staticfiles %}{% load bootstrap3 %}

{% block css_head %}
		{{ form.media.css }}
		<link rel="stylesheet" type="text/css" href="{% static 'css/select2.css' %}">
{% endblock %}

{% block content %}
{% if form %}
	<form id="sessao" role="form" action="{% url 'sessao' %}" method="post" style="margin-bottom: 20px;">
		<div class="well">
			<button type="submit" class="btn btn-success" name="salvar" id="salvar"><i class="fa fa-edit" aria-hidden="true"></i> Salvar</button>
			<button type="submit" class="btn btn-default" name="salvar_sair" id="salvar_sair"><i class="fa fa-save" aria-hidden="true"></i> Salvar e Sair</button>
			<button type="submit" class="btn btn-default" name="salvar_novo" id="salvar_novo"><i class="fa fa-plus" aria-hidden="true"></i> Salvar e Criar Novo </button>
			<button type="button" class="btn btn-default" name="cancelar" id="cancelar"><i class="fa fa-reply" aria-hidden="true"></i> Cancelar e Voltar</button>

			{% if form.key.value %}
			<button type="button" class="btn btn-danger pull-right" data-toggle="modal" data-target="#modalExcluir" data-sessao="{{form.nome.value}}" data-id="{{form.key.value}}"><i class="fa fa-times" aria-hidden="true"></i> Deletar</button>
			{% endif %}
		</div>
		{% csrf_token %}
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			{% bootstrap_form form layout='horizontal' %}
			</div>
		</div>
	</form>
	<div class="modal fade" id="modalExcluir" tabindex="-1" role="dialog" aria-labelledby="modalExcluir">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">Atenção</h4>
				</div>
				<div class="modal-body">
					Deseja excluir a sessão <span id="sessaoId"></span>?
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					<button type="button" class="btn btn-danger" id="excluir">Excluir</button>
				</div>
			</div>
		</div>
	</div>
{% endif %}

{% endblock %}

{% block scripts %}
{{ form.media.js }}
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

<script type="text/javascript">
	$( function() {
		$( "#id_data" ).datepicker({
			format: "dd/mm/yyyy"
		});
	} );
</script>

<script type="text/javascript">

	$(document).ready(function(){
		var csrftoken = $.cookie('csrftoken');

		function csrfSafeMethod(method) {
			// these HTTP methods do not require CSRF protection
			return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
		}

		$.ajaxSetup({
			beforeSend: function(xhr, settings) {
				if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
					xhr.setRequestHeader("X-CSRFToken", csrftoken);
				}
			}
		});

		/*
		** Prepara os dados dos tópicos
		*/
		var $select = $('.django-select2').djangoSelect2({
			data: {{ topicos_interesse | safe }},
		});

		{% if topicos %}
			$select.val({{ topicos | safe }}).trigger("change");
		{% endif %}

		/*
		** Prepara o datepicker
		*/
		$('#id_data').datepicker({
			format: "dd/mm/yyyy"
		});

		/*
		** O botão cancelar faz voltar pra tela das sessões
		*/
		$('#cancelar').click(function (event) {
			window.location = "{% url 'sessoes' %}";
		});

		$('#modalExcluir').on('show.bs.modal', function (event) {
			var sessao = $("#sessaoId");
			var nome = $(event.relatedTarget).data('sessao');
			var id = $(event.relatedTarget).data('id');
			sessao.text(nome);
			$('#excluir').click(function (event) {
				$.ajax({
					url: "{% url 'excluir_sessao' %}",
					data: {item: id},
					type: 'POST',
					success: function(data){
						window.location = "{% url 'sessoes' %}";
					}
				});
			});
		});
	});
</script>

{% endblock %}

sessao/templates/sessoes.html
{% extends "base.html" %}

{% block content %}
<div class="well">
	<a href="{% url 'sessao' %}" class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i>
Nova Sessão</a>
</div>
{% if sessoes %}
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="table-responsive">
				<table class="table table-bordered table-striped table-condensed">
					<thead>
						<tr>
							<th>Nome</th>
							<th>Descrição</th>
							<th>Sala</th>
							<th width="57px">Ações</th>
						</tr>
					</thead>
				{% for sessao in sessoes %}
					<tr>
						<td>
							<dl>
								<dt><a href="{% url 'sessao' %}?key={{ sessao.key }}">{{ sessao.nome }}</a></dt>
								<dd></dd>
							</dl>
						</td>
						<td>
							{{ sessao.descricao|truncatewords:20 }}
						</td>
						<td>
							{{ sessao.sala }}
						</td>
						<td>
							<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalExcluir" data-sessao="{{ sessao.nome }}" data-id="{{ sessao.key }}">
								<i class="fa fa-times" aria-hidden="true"></i>
							</button>
						</td>
					</tr>
				{% endfor%}
				</table>
				</div>
		</div>
	</div>
	<div class="modal fade" id="modalExcluir" tabindex="-1" role="dialog" aria-labelledby="modalExcluir">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">Atenção</h4>
				</div>
				<div class="modal-body">
					Deseja excluir a sessão <span id="sessaoId"></span>?
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					<button type="button" class="btn btn-danger" id="excluir">Excluir</button>
				</div>
			</div>
		</div>
	</div>
{% endif %}

{% endblock %}

{% block scripts %}
<script type="text/javascript">

	$(document).ready(function(){
		var csrftoken = $.cookie('csrftoken');

		function csrfSafeMethod(method) {
			// these HTTP methods do not require CSRF protection
			return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
		}

		$.ajaxSetup({
			beforeSend: function(xhr, settings) {
				if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
					xhr.setRequestHeader("X-CSRFToken", csrftoken);
				}
			}
		});

		$('#modalExcluir').on('show.bs.modal', function (event) {
			var sessao = $("#sessaoId");
			var nome = $(event.relatedTarget).data('sessao');
			var id = $(event.relatedTarget).data('id');
			sessao.text(nome);
			$('#excluir').click(function (event) {
				$.ajax({
					url: "{% url 'excluir_sessao' %}",
					data: {item: id},
					type: 'POST',
					success: function(data){
						window.location = "{% url 'sessoes' %}";
					}
				});
			});
		});
	});
</script>
{% endblock %}