EventManager/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^', include('sessao.urls')),
	url(r'^', include('recomendacao.urls')),
	url(r'^', include('topicos.urls')),
	url(r'^', include('login.urls')),
	url(r'^', include('trabalho.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/urls.py
from django.conf.urls import url

from django.contrib.auth import views
from .forms import LoginForm, UpdatePasswordForm

urlpatterns = [
  url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
  url(r'^trocar_senha/$', views.password_change,
    {
      'template_name': 'trocar_senha.html',
      'password_change_form': UpdatePasswordForm,
      'post_change_redirect': 'change_password',
    },
    name='change_password'),
  url(r'^logout/$', views.logout, {'next_page': 'login'}, name='logout'),
]

trabalho/urls.py
from django.conf.urls import url

from .views import Trabalho, trabalhos, excluir_trabalho

urlpatterns = [
	url(r'^trabalho/$', Trabalho.as_view(), name='trabalho'),
  url(r'^trabalhos/$', trabalhos, name='trabalhos'),
  url(r'^excluir_trabalho/$', excluir_trabalho, name='excluir_trabalho'),
]

trabalho/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import ast
from django.core.validators import MaxValueValidator, MinValueValidator

from django.db import models
from firebase.backend import firebase

TIPO = (
	('AR', 'Artigo Resumido'),
	('AC', 'Artigo Completo'),
	('AP', 'Artigo IHC na Prática')
)

class Trabalho(models.Model):
	class Meta:
		verbose_name = "Trabalho"
		verbose_name_plural = "Trabalhos"

	key = models.CharField(max_length=30, editable=False)
	titulo = models.CharField(max_length=400)
	tipo = models.CharField(max_length=25, blank=True)
	ordem = models.PositiveIntegerField(validators=[MaxValueValidator(20), MinValueValidator(1)])
	sessao = models.CharField(max_length=30)
	sessao_antiga = models.CharField(max_length=30, blank=True)
	autores = models.CharField(max_length=400)

	def __unicode__(self):
		return self.titulo

	def save(self, *args, **kwargs):
		db = firebase.database()

		autores = ast.literal_eval(self.autores)
		tipo = ''
		for i in range(len(TIPO)):
			if TIPO[i][0] == self.tipo:
				tipo = TIPO[i][1]
				break

		dados = {
			'titulo': self.titulo,
			'tipo': tipo,
			'ordem': self.ordem,
			'autores': autores
		}

		if not self.key:
			salvo = db.child('sessoes').child(self.sessao).child('trabalhos').push(dados)
			self.key = salvo['name']
		else:
			if self.sessao != self.sessao_antiga:
				db.child('sessoes').child(self.sessao_antiga).child('trabalhos').child(self.key).remove()
			db.child('sessoes').child(self.sessao).child('trabalhos').child(self.key).update(dados)

	def delete(self):
		db = firebase.database()
		db.child('sessoes').child(self.sessao).child('trabalhos').child(self.key).remove()

trabalho/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Trabalho
from django_select2.forms import Select2Widget, Select2MultipleWidget

class TrabalhoForm(forms.ModelForm):

	TIPO = (
		('', ''),
		('AR', 'Artigo Resumido'),
		('AC', 'Artigo Completo'),
		('AP', 'Artigo IHC na Prática')
	)

	key = forms.CharField(widget=forms.HiddenInput(), required=False)
	titulo = forms.CharField(label='Título', widget=forms.TextInput(attrs={'class': 'form-control'}))
	tipo = forms.CharField(label='Tipo', widget=Select2Widget(choices=TIPO, attrs={'class': 'form-control'}), required=False)
	ordem = forms.CharField(label='Ordem', widget=forms.NumberInput(attrs={'class': 'form-control', 'min': 1, 'max': 20}))
	sessao = forms.CharField(label='Sessão', widget=Select2Widget)
	sessao_antiga = forms.CharField(widget=forms.HiddenInput(), required=False)
	autores = forms.CharField(label='Autores', widget=forms.SelectMultiple(attrs={'data-role': 'tagsinput', 'class': 'form-control'}))

	class Meta:
		model = Trabalho
		fields = '__all__'

trabalho/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import logging
import json

from django.shortcuts import render, redirect
from django.http import Http404, HttpResponseForbidden, HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.views import View
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from firebase.backend import firebase
from .models import Trabalho
from .forms import TrabalhoForm

logger = logging.getLogger(__name__)

TIPO = (
	('AR', 'Artigo Resumido'),
	('AC', 'Artigo Completo'),
	('AP', 'Artigo IHC na Prática')
)

class Trabalho(View):
	@method_decorator(login_required)
	def get(self, request):
		db = firebase.database()
		# pega as sessões para popular no template
		sessoes_db = db.child('sessoes').get()
		sessoes = []
		for t in sessoes_db.each():
			try:
				sessao = {}
				sessao['text'] = t.val()['nome']
				sessao['id'] = t.key()
				sessoes.append(sessao)
			except Exception as e:
				logger.warning('Erro com a Sessão: %s', e)
		sessoes_sorted = sorted(sessoes, key=lambda k: k['text'])
		sessoes_sorted.insert(0, {'id': '', 'text': ''})
		# inicia a criação do formulário
		try:
			# caso exista uma key, será retornado um form populado com as informações do firebase para edição
			key = request.GET.get('key')
			sessao_selecionada = ''
			for sessao in sessoes_db.each():
				try:
					for trabalho in sessao.val()['trabalhos'].items():
						if trabalho[0] == key:
							sessao_selecionada = sessao.key()
				except Exception as e:
					pass

			trabalho_db = db.child('sessoes').child(sessao_selecionada).child('trabalhos').child(key).get().val()

			tipo = ''
			for i in range(len(TIPO)):
				if TIPO[i][1] == trabalho_db['tipo']:
					tipo = TIPO[i][0]
					break

			# popula o form com as informações da sessão
			form = TrabalhoForm(
				initial={
					'key': key,
					'titulo': trabalho_db['titulo'],
					'ordem': trabalho_db['ordem'],
					'sessao_antiga': sessao_selecionada
				}
			)
			# prepara o conteúdo que vai pro template
			# pra chamar no template tem que usar o nome que está entre aspas simples
			contexto = {
				'form': form,
				'sessao_selecionada': sessao_selecionada,
				'tipo': tipo,
				'autores': trabalho_db['autores'],
				'sessoes': json.dumps(sessoes_sorted),
			}
		except Exception as e:
			# do contrário, será retornado um form vazio, que será usado para a criação de um novo objeto
			form = TrabalhoForm()

			contexto = {
				'form': form,
				'sessoes': json.dumps(sessoes_sorted),
			}

		return render(request, 'trabalho.html', contexto)

	@method_decorator(login_required)
	def post(self, request):
		form = TrabalhoForm(request.POST or None)
		if form.is_valid():
			#vai pegar a key, mesmo que ela seja vazia
			#caso a key seja vazia, é sinal de que o objeto é novo
			key = form.cleaned_data['key']
			#cria um objeto mas não salva, pois o commit=False
			trabalho = form.save(commit=False)
			#Esse objeto não tem uma key definida, mas a key existe no formulário
			#Então é necessário passar a key da sessão editada para que uma nova sessão não seja criada
			trabalho.key = key
			#salva o objeto editado
			trabalho.save()
			logger.info('Trabalho salvo com sucesso: %s', trabalho.key)
			messages.success(request, 'Trabalho salvo com sucesso!')

			if 'salvar' in request.POST:
				url = reverse('trabalho')
				return redirect(url + '?key=' + trabalho.key)
			elif 'salvar_novo' in request.POST:
				return redirect('trabalho')
			else:
				return redirect('trabalhos')
		else:
			contexto = {'form': form}
			return render(request, 'trabalho.html', contexto)

@login_required
def excluir_trabalho(request):
	if request.method == 'POST':
		db = firebase.database()
		item = request.POST.get('item')
		sessao = request.POST.get('sessao')
		trabalho = db.child('sessoes').child(sessao).child('trabalhos').child(item).get().val()
		if trabalho:
			db.child('sessoes').child(sessao).child('trabalhos').child(item).remove()
			messages.success(request, 'Trabalho removido com sucesso!')
			return HttpResponse('True')
		else:
			messages.error(request, 'Erro ao remover o trabalho!')
			return HttpResponse('False')
	else:
		return redirect('trabalhos')

@login_required
def trabalhos(request):
	db = firebase.database()
	sessoes_fb = db.child('sessoes').get()

	trabalhos = []
	for sessao in sessoes_fb.each():
		try:
			trabalhos_fb = sessao.val()['trabalhos']
			for key, trabalho in trabalhos_fb.items():
				try:
					novo_trabalho = {}
					novo_trabalho['key'] = key
					novo_trabalho['titulo'] = trabalho['titulo']
					novo_trabalho['sessao'] = sessao.val()['nome']
					novo_trabalho['sessao_key'] = sessao.key()
					novo_trabalho['tipo'] = trabalho['tipo']
					trabalhos.append(novo_trabalho)
				except KeyError as e:
					logger.error('Não foi possível carregar o trabalho: %s', e)
		except TypeError as e:
			logger.info('Não existem trabalhos na sessão. Erro: %s', e)
		except KeyError as e:
			logger.info('Não existem trabalhos na sessão. Erro: %s', e)

	# Cria o sistema de paginação
	paginator = Paginator(trabalhos, 20) # mostra 20 trabalhos por página
	pagina = request.GET.get('page')

	try:
		lista_trabalhos = paginator.page(pagina)
	except PageNotAnInteger:
		# se a página não for um inteiro, mostra a primeira
		pagina = 1
	except EmptyPage:
		# se a página for fora do intervalo, mostra a primeira
		if int(pagina) <= 0:
			pagina = 1
		else:
			pagina = paginator.num_pages

	pagina = int(pagina)
	lista_trabalhos = paginator.page(pagina)

	range_min = 1 if (pagina - 1 <= 0) else (pagina - 1)
	range_max = paginator.num_pages + 1 if (pagina + 2 > paginator.num_pages) else (pagina + 2)
	range_paginas = xrange(range_min, range_max)

	contexto = {'trabalhos': lista_trabalhos, 'range_paginas': range_paginas, 'penultima_pagina': paginator.num_pages-1}

	return render(request, 'trabalhos.html', contexto)

trabalho/templates/trabalho.html
{% extends "base.html" %}
{% load staticfiles %}{% load bootstrap3 %}

{% block css_head %}
		{{ form.media.css }}
		<link rel="stylesheet" type="text/css" href="{% static 'css/select2.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-tagsinput.css' %}">
{% endblock %}

{% block content %}
{% if form %}
	<form id="trabalho" role="form" action="{% url 'trabalho' %}" method="post" style="margin-bottom: 20px;">
		<div class="well">
			<button type="submit" class="btn btn-success" name="salvar" id="salvar"><i class="fa fa-edit" aria-hidden="true"></i> Salvar</button>
			<button type="submit" class="btn btn-default" name="salvar_sair" id="salvar_sair"><i class="fa fa-save" aria-hidden="true"></i> Salvar e Sair</button>
			<button type="submit" class="btn btn-default" name="salvar_novo" id="salvar_novo"><i class="fa fa-plus" aria-hidden="true"></i> Salvar e Criar Novo </button>
			<button type="button" class="btn btn-default" name="cancelar" id="cancelar"><i class="fa fa-reply" aria-hidden="true"></i> Cancelar e Voltar</button>

			{% if form.key.value %}
			<button type="button" class="btn btn-danger pull-right" data-toggle="modal" data-target="#modalExcluir" data-trabalho="{{form.titulo.value}}" {% if sessao_selecionada %} data-sessao="{{ sessao_selecionada | safe }}" {% endif %} data-id="{{form.key.value}}"><i class="fa fa-times" aria-hidden="true"></i> Deletar</button>
			{% endif %}
		</div>
		{% csrf_token %}
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			{% bootstrap_form form layout='horizontal' %}
			</div>
		</div>
	</form>
	<div class="modal fade" id="modalExcluir" tabindex="-1" role="dialog" aria-labelledby="modalExcluir">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">Atenção</h4>
				</div>
				<div class="modal-body">
					Deseja excluir o trabalho <span id="trabalhoId"></span>?
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					<button type="button" class="btn btn-danger" id="excluir">Excluir</button>
				</div>
			</div>
		</div>
	</div>
{% endif %}
{% endblock %}

{% block scripts %}
{{ form.media.js }}
<script src="{% static 'js/bootstrap-tagsinput.js' %}"></script>

<script type="text/javascript">

	$(document).ready(function(){
		var csrftoken = $.cookie('csrftoken');

		function csrfSafeMethod(method) {
			// these HTTP methods do not require CSRF protection
			return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
		}

		$.ajaxSetup({
			beforeSend: function(xhr, settings) {
				if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
					xhr.setRequestHeader("X-CSRFToken", csrftoken);
				}
			}
		});

		{% if autores %}
			{% for autor in autores %}
				$('#id_autores').tagsinput('add', '{{autor}}');
			{% endfor %}
		{% endif %}

		$('.bootstrap-tagsinput > input').focusin(function() {
			$(this).parent().addClass('bootstrap-tagsinput--focus');
		});
		$('.bootstrap-tagsinput > input').focusout(function() {
			$(this).parent().removeClass('bootstrap-tagsinput--focus');
		});

		/*
		** Prepara os dados das sessões
		*/
		var $select = $('#id_sessao').djangoSelect2({
			placeholder: "Selecione uma Sessão",
			data: {{ sessoes | safe }}
		});

		{% if sessao_selecionada %}
			$select.val('{{ sessao_selecionada | safe }}').trigger("change");
		{% endif %}

		$('#id_tipo').djangoSelect2({
			placeholder: "Selecione um Tipo"
		});

		{% if tipo %}
			$('#id_tipo').val('{{tipo}}').trigger("change");
		{% endif %}

		/*
		** O botão cancelar faz voltar pra tela das sessões
		*/
		$('#cancelar').click(function (event) {
			window.location = "{% url 'trabalhos' %}";
		});

		$('#modalExcluir').on('show.bs.modal', function (event) {
			var sessao = $(event.relatedTarget).data('sessao');
			var trabalho = $('#trabalhoId');
			var nome = $(event.relatedTarget).data('trabalho');
			var id = $(event.relatedTarget).data('id');
			trabalho.text(nome);
			$('#excluir').click(function (event) {
				$.ajax({
					url: "{% url 'excluir_trabalho' %}",
					data: {item: id, sessao: sessao},
					type: 'POST',
					success: function(data){
						window.location = "{% url 'trabalhos' %}";
					}
				});
			});
		});
	});
</script>

{% endblock %}

trabalho/templates/trabalhos.html
{% extends "base.html" %}

{% block content %}
<div class="well">
	<a href="{% url 'trabalho' %}" class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i> Novo Trabalho</a>
</div>
{% if trabalhos %}
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="table-responsive">
				<table class="table table-bordered table-striped table-condensed">
					<thead>
						<tr>
							<th>Nome</th>
							<th>Tipo</th>
							<th>Sessão</th>
							<th width="57px">Ações</th>
						</tr>
					</thead>
				{% for trabalho in trabalhos %}
					<tr>
						<td>
							<dl>
								<dt><a href="{% url 'trabalho' %}?key={{ trabalho.key }}">{{ trabalho.titulo }}</a></dt>
								<dd></dd>
							</dl>
						</td>
						<td>
							{{ trabalho.tipo }}
						</td>
						<td>
							{{ trabalho.sessao }}
						</td>
						<td>
							<button type="button" class="btn btn-danger pull-right" data-toggle="modal" data-target="#modalExcluir" data-trabalho="{{ trabalho.titulo }}" data-sessao="{{ trabalho.sessao_key }}" data-id="{{ trabalho.key }}">
								<i class="fa fa-times" aria-hidden="true"></i>
							</button>
						</td>
					</tr>
				{% endfor%}
				</table>
				</div>
		</div>
	</div>
	{% if trabalhos.paginator.num_pages > 1 %}
	<nav aria-label="Page navigation">
		<ul class="pagination">
			{% if trabalhos.has_previous %}
			<li><a href="?page={{ trabalhos.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
				{% if trabalhos.previous_page_number != 1 %}
				<li><a href="?page=1">1</a></li>
					{% if range_paginas|first != 2 %}
					<li><span>...</span></li>
					{% endif %}
				{% endif %}
			{% else %}
			<li class="disabled"><span aria-hidden="true" aria-label="Previous">&laquo;</span></li>
			{% endif %}

			{% for page in range_paginas %}
				{% if page == trabalhos.number %}
				<li class="active"><a href="#">{{ page }} <span class="sr-only">(current)</span></a></li>
				{% else %}
				<li><a href="?page={{ page }}">{{ page }}</a></li>
				{% endif %}
			{% endfor %}

			{% if trabalhos.has_next %}
				{% if trabalhos.next_page_number != trabalhos.paginator.num_pages %}
					{% if range_paginas|last != penultima_pagina %}
					<li><span>...</span></li>
					{% endif %}
				<li><a href="?page={{ trabalhos.paginator.num_pages }}">{{ trabalhos.paginator.num_pages }}</a></li>
				{% endif %}
			<li><a href="?page={{ trabalhos.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
			{% else %}
			<li class="disabled"><span aria-hidden="true" aria-label="Next">&raquo;</span></li>
			{% endif %}
		</ul>
	</nav>
	{% endif %}
	<div class="modal fade" id="modalExcluir" tabindex="-1" role="dialog" aria-labelledby="modalExcluir">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">Atenção</h4>
				</div>
				<div class="modal-body">
					Deseja excluir o trabalho "<span id="trabalhoId"></span>"?
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					<button type="button" class="btn btn-danger" id="excluir">Excluir</button>
				</div>
			</div>
		</div>
	</div>
{% endif %}

{% endblock %}

{% block scripts %}
<script type="text/javascript">

	$(document).ready(function(){
		var csrftoken = $.cookie('csrftoken');

		function csrfSafeMethod(method) {
			// these HTTP methods do not require CSRF protection
			return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
		}

		$.ajaxSetup({
			beforeSend: function(xhr, settings) {
				if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
					xhr.setRequestHeader("X-CSRFToken", csrftoken);
				}
			}
		});

		$('#modalExcluir').on('show.bs.modal', function (event) {
			var sessao = $(event.relatedTarget).data('sessao');
			var trabalho = $('#trabalhoId');
			var nome = $(event.relatedTarget).data('trabalho');
			var id = $(event.relatedTarget).data('id');
			trabalho.text(nome);
			$('#excluir').click(function (event) {
				$.ajax({
					url: "{% url 'excluir_trabalho' %}",
					data: {item: id, sessao: sessao},
					type: 'POST',
					success: function(data){
						window.location = "{% url 'trabalhos' %}";
					}
				});
			});
		});
	});
</script>
{% endblock %}